# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_book_seat_movies_movie_id_book_post(self) -> None:
        """Test case for book_seat_movies_movie_id_book_post

        Book Seat
        """
        pass

    def test_create_movie_movies_post(self) -> None:
        """Test case for create_movie_movies_post

        Create Movie
        """
        pass

    def test_delete_movie_movies_movie_id_delete(self) -> None:
        """Test case for delete_movie_movies_movie_id_delete

        Delete Movie
        """
        pass

    def test_get_bookings_movies_movie_id_bookings_get(self) -> None:
        """Test case for get_bookings_movies_movie_id_bookings_get

        Get Bookings
        """
        pass

    def test_get_movies_movies_get(self) -> None:
        """Test case for get_movies_movies_get

        Get Movies
        """
        pass

    def test_home_get(self) -> None:
        """Test case for home_get

        Home
        """
        pass

    def test_test_test_get(self) -> None:
        """Test case for test_test_get

        Test
        """
        pass


if __name__ == '__main__':
    unittest.main()
